### ISSUE TITLE
VisData messages queued in webworker aren't cancelled when changing trajectories

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/simularium-viewer#163]
## Description

It is possible to have queued agent data from a previous trajectory still arriving (and rendering!) AFTER changing trajectories.

I already diagnosed this:  the POINTS TEST returns data on a very fast interval, and each message gets queued in a webworker.  Because so many get queued, and yet the webworker has to do a lot of processing, the worker just keeps chugging away long after you change trajectories, and when the worker finishes, it sticks its data in the VisData frame cache ready for updating in the scene.

## Expected Behavior

Changing trajectories should completely forget about the previous one.

## Reproduction

Load example viewer.
Select the POINTS TEST and click Load model.
Press Play.
Press Pause.
Fairly quickly, change to "Medyan test" and Load model.
See the rendered display continue to draw frames from the POINTS TEST.

**Comment by schoinh** [comment]
Ooh, wonder if fixing this would take care of this bug? https://github.com/allen-cell-animated/simularium-website/issues/160
