### ISSUE TITLE
Prototype file conversion

### ISSUE THREAD

**Issue by blairlyons** [allen-cell-animated/simularium-viewer#165]
## Use Case
It would be nice for developers to be able to test locally loading output files from supported simulation engines directly in the Viewer without converting them to .simularium format first.

## Acceptance Criteria
Users can provide the same input data they would provide to any of the converters in SimulariumIO (except the plain `TrajectoryConverter`) using a UI and see the data load in the Viewer.

## Details
Implement this in the current example app included with the viewer.

Data that will need to be captured from the user is shown in the example Jupyter notebook for each supported simulator https://github.com/allen-cell-animated/simulariumio/tree/main/examples. This will mostly require text fields and file dialogs or drag/drop targets for capturing config and files.

Use SimulariumIO (https://github.com/allen-cell-animated/simulariumio) to convert the file given the input data and config. Set up a lambda, here's an example of returning data to a client https://docs.aws.amazon.com/apigateway/latest/developerguide/lambda-proxy-binary-media.html. 

Load the data that is returned in the viewer.

This prototype will help us work toward allowing users, especially non-computational users, to skip converting data in Python first.

**Comment by schoinh** [comment]
We now have web API endpoints available for converting Smoldyn, SpringSalad, Medyan, and CytoSim
