### ISSUE TITLE
Perfectly aligned fiber does not render

### ISSUE THREAD

**Issue by blairlyons** [allen-cell-animated/simularium-viewer#170]
## Description
If a fiber is aligned perfectly with an axis of the view, it does not render.

## Expected Behavior
Fiber should render regardless of its subpoint positions.

## Reproduction
The only difference between these two files is one of the fiber's z positions.
fiber_on_axis: filament at [-70, 0, 0] to [10, 0, 0]
fiber_off_axis: filament at [-70, 0, 0] to [10, 0, 0.001]
[fiber.zip](https://github.com/allen-cell-animated/simularium-viewer/files/6957548/fiber.zip)

## Environment
Can reproduce on production and staging

**Comment by toloudis** [comment]
Even a filament from [-70, 0, 0.001] to [10, 0, 0.001] will render correctly even though it is "on axis" by all definitions!
Curves from (x, 0, epsilon) to (x+length, 0, epsilon) seem to be fine.  Still testing and trying to figure out why this is ok.  I'm not above putting a tiny fudge factor in the code but will try to find a true solution first.

**Comment by toloudis** [comment]
Tracked it down finally. Fix is coming up
